import argparse
import os
import subprocess
import sys
from pathlib import Path

import yaml


class AgentRunner:
    """Minimal runner that interprets a manifest and instructions to scaffold a project."""

    def __init__(self, manifest_path: str, instructions_path: str, output: str = "generated_project"):
        self.manifest = yaml.safe_load(Path(manifest_path).read_text())
        self.instructions = Path(instructions_path).read_text()
        self.output = Path(output)

    def log(self, *parts):
        print("[agent]", *parts)

    def ensure_output(self):
        self.output.mkdir(parents=True, exist_ok=True)

    def write_file(self, rel_path: str, content: str):
        path = self.output / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        self.log("Wrote", path)

    def run_cmd(self, cmd, cwd=None):
        cwd = cwd or self.output
        self.log("Running:", cmd)
        res = subprocess.run(cmd, shell=True, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        out = res.stdout.decode(errors="replace")
        self.log(out.strip())
        return res.returncode, out

    def init_git(self):
        if (self.output / ".git").exists():
            self.log("Git repo already exists")
            return
        self.run_cmd("git init")
        self.run_cmd("git add -A")
        self.run_cmd("git commit -m \"chore: initial scaffold by agent\"")

    def scaffold_fastapi(self):
        # minimal files
        self.write_file("requirements.txt", "fastapi\nuvicorn[standard]\nbehave\n")
        self.write_file("README.md", "# Generated FastAPI Project\n\nGenerated by Senior FastAPI Developer agent.\n")
        self.write_file("app/main.py", "from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get('/')\nasync def root():\n    return {'status': 'ok'}\n")
        # BDD feature
        feature_text = '''Feature: Health check
  Scenario: Root returns OK
    Given the server is running
    When I request the root endpoint
    Then the response status should be 200
    And the response should contain "status"
'''
        self.write_file("features/health_check.feature", feature_text)
        # behave steps using TestClient
        steps_text = '''from behave import given, when, then
from fastapi.testclient import TestClient
from app.main import app


@given('the server is running')
def step_server_running(context):
    context.client = TestClient(app)


@when('I request the root endpoint')
def step_request_root(context):
    context.response = context.client.get('/')


@then('the response status should be 200')
def step_check_status(context):
    assert context.response.status_code == 200


@then('the response should contain "{key}"')
def step_check_body(context, key):
    assert key in context.response.json()
'''
        self.write_file("features/steps/health_steps.py", steps_text)

    def run(self):
        self.ensure_output()
        self.log("Manifest:", self.manifest.get("id"))
        # For now, only implement project-scaffold capability
        if "project-scaffold" in self.manifest.get("capabilities", []) or "project-scaffold" in self.manifest.get("capabilities", []):
            self.log("Scaffolding FastAPI project into", str(self.output))
            self.scaffold_fastapi()
            self.init_git()
            self.log("Scaffold complete")
        else:
            self.log("No scaffold capability found in manifest")


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--agent", required=True)
    parser.add_argument("--instructions", required=True)
    parser.add_argument("--output", default="generated_project")
    args = parser.parse_args(argv)
    runner = AgentRunner(args.agent, args.instructions, output=args.output)
    runner.run()


if __name__ == "__main__":
    main()
